### ISSUE TITLE
**short summary**

### ISSUE THREAD

**Issue by bacheral** [nager/Nager.Date#385]
### Affected country

ES

### Affected public holiday

Fiesta del trabajo

### Source of the information

https://es.wikipedia.org/wiki/D%C3%ADa_Internacional_de_los_Trabajadores

### More information

Please change the parameter 'fixed' from "false' to "true" for 'Fiesta del trabajo'.
This public holiday is not moved from a weekend to workdays, it's fixed on 1st of May, always.

**Comment by bacheral** [comment]
same one btw for Fiesta de la Comunidad de Madrid -> this should be fixed as well to May 2nd

    {
        "date": "2022-05-03",
        "localName": "Fiesta de la Comunidad de Madrid",
        "name": "Day of Madrid",
        "countryCode": "ES",
        "fixed": false,
        "global": false,
        "counties": [
            "ES-M"
        ],
        "launchYear": null,
        "types": [
            "Public"
        ]
    },

**Comment by tinohager** [comment]
Source:
https://github.com/nager/Nager.Date/blob/master/src/Nager.Date/PublicHolidays/SpainProvider.cs

"Fiesta del trabajo" has a day shift for weekend is not fixed
"Fiesta de la Comunidad de Madrid" is shifted if it on the same day as "Fiesta del trabajo"

**Comment by tinohager** [comment]
@fidelpita you can also agree to the changes?

**Comment by tinohager** [comment]
@bacheral i have add a code update, please check

**Comment by bacheral** [comment]
> @bacheral i have add a code update, please check

I've checked it thanks, would be an improvement like this for my understanding.
